"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { ArrowDownLeft, ArrowUpRight, Send } from "lucide-react";
import Sidebar from "@/components/Sidebar"; import { useAuth } from "@/components/AuthProvider"; import { api, ApiError } from "@/lib/api";
type Account={id:number;account_number:string;name:string;type:string;currency:string;balance:number;status:string};
type Tx={id:number;reference:string;counterparty:string;amount:number;direction:string;category:string;description:string;created_at:string;status:string};
export default function AccountsPage(){const {ready}=useAuth();const router=useRouter();const [accounts,setAccounts]=useState<Account[]>([]);const [txs,setTxs]=useState<Tx[]>([]);const [error,setError]=useState("");
useEffect(()=>{if(!ready)return;Promise.all([api<Account[]>("/accounts"),api<Tx[]>("/transactions")]).then(([a,t])=>{setAccounts(a);setTxs(t)}).catch(e=>{if(e instanceof ApiError&&e.status===401)router.push("/login");else setError(e.message)})},[ready,router]);
const fmt=(n:number,c="EUR")=>new Intl.NumberFormat("en-GB",{style:"currency",currency:c}).format(n);
return <div className="flex min-h-screen bg-[#080e1a] text-white"><Sidebar/><main className="min-w-0 flex-1 p-5 lg:p-9"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.25em] text-cyan-400">Treasury workspace</p><h1 className="mt-2 text-4xl font-bold">Accounts</h1><p className="mt-2 text-slate-400">Available cash and settled ledger activity.</p></div><Link href="/transfers" className="flex items-center gap-2 rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950"><Send size={18}/>New payment</Link></div>{error&&<p className="mt-6 rounded-xl bg-red-500/10 p-4 text-red-300">{error}</p>}<section className="mt-8 grid gap-5 lg:grid-cols-2">{accounts.map(a=><article key={a.id} className="relative overflow-hidden rounded-2xl border border-white/10 bg-gradient-to-br from-slate-800 to-slate-900 p-6"><div className="absolute -right-12 -top-12 h-40 w-40 rounded-full bg-cyan-400/10"/><div className="flex justify-between"><div><p className="text-sm text-slate-400">{a.type} · •••• {a.account_number.slice(-4)}</p><h2 className="mt-1 text-lg font-semibold">{a.name}</h2></div><span className="h-fit rounded-full bg-emerald-400/10 px-3 py-1 text-xs text-emerald-300">{a.status}</span></div><p className="mt-10 text-sm text-slate-400">Available balance</p><p className="mt-1 text-3xl font-bold">{fmt(a.balance,a.currency)}</p></article>)}</section><section className="mt-8 overflow-hidden rounded-2xl border border-white/10 bg-[#101827]"><div className="border-b border-white/10 p-5"><h2 className="text-lg font-semibold">Recent transactions</h2></div><div className="divide-y divide-white/5">{txs.map(t=><div key={t.id} className="flex items-center gap-4 p-4 sm:p-5"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${t.direction==="credit"?"bg-emerald-400/10 text-emerald-300":"bg-slate-700 text-slate-300"}`}>{t.direction==="credit"?<ArrowDownLeft/>:<ArrowUpRight/>}</span><div className="min-w-0 flex-1"><p className="truncate font-medium">{t.counterparty}</p><p className="truncate text-xs text-slate-500">{t.description} · {new Date(t.created_at).toLocaleDateString()}</p></div><div className="text-right"><p className={t.amount>0?"font-semibold text-emerald-300":"font-semibold"}>{t.amount>0?"+":""}{fmt(t.amount)}</p><p className="text-xs text-slate-500">{t.status}</p></div></div>)}</div></section></main></div>}
